# Change these first
owner: ovrap3x # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Sec
    url: https://sec.wehasinter.net
  - name: Wiki
    url: https://wiki.wehasinter.net
  - name: cloud
    check: "tcp-ping"
    url: 5.196.67.228
    port: 80
  - name: stenberg.im mx
    check: "tcp-ping"
    url: 5770e78ab2744d97f1aa00df2a160c.pamx1.hotmail.com
    port: 25
  - name: stenberg.im mx ssl
    check: "tcp-ping"
    url: 5770e78ab2744d97f1aa00df2a160c.pamx1.hotmail.com
    port: 587
  - name: stenberg.im mx startls
    check: "tcp-ping"
    url: 5770e78ab2744d97f1aa00df2a160c.pamx1.hotmail.com
    port: 465
status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wehasinter.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** status of stuff and things"
  introMessage: This is a sample status page 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
